FROM alpine:3.22

# Workdir commun
WORKDIR /app

# Install des dépendances communes
RUN apt-get update -y && apt-get install -y python



# build for dev
FROM python:3.11-slim AS dev

VOLUME [ "./src/rally-main/rally_back"]

COPY ./requirements.txt .

RUN pip install --upgrade pip && pip install -r ./requirements.txt

ENV ENVIRONMENT=development

CMD ["python", "main.py"]


# build for prod
FROM python:3.11-slim AS prod

COPY ./src/rally-main/rally_back . \
    ./requirements.txt ./

RUN pip install --upgrade pip && pip install -r ./requirements.txt

ENV ENVIRONMENT=production

ENTRYPOINT ["python", "main.py"]