services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: rally
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rally-network

  rally-back:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    env_file:
      - .env
    container_name: back
    ports:
      - "8000:8000"
    volumes:
      - ./src/rally-main/rally_back:/rally_back
    networks:
      - rally-network

networks:
  rally-network:
    driver: bridge

volumes:
  pgdata:
