FROM python:3.11-slim

WORKDIR /app

VOLUME [ "./src/rally-main/rally_back"]

COPY ./requirements.txt .

RUN pip install --upgrade pip && pip install -r ./requirements.txt

ENV ENVIRONMENT=development

CMD  ["python", "main.py"]
