name: Vitest rally_front

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./rally_front

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: ./rally_front/package-lock.json

      - name: Clean node_modules and package-lock (fix Rollup native error)
        run: |
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Run Vitest tests
        run: npm run test
