name: CI rally_back

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-dependencies:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        working-directory: .
        run: pip install -r requirements.txt

  lint:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.12"]

          steps:
          - name: Analysing the code with pylint
            working-directory: ./src/rally-main/rally_back
            run: pylint .

  sanning-for-secrets:
      runs-on: ubuntu-latest
      strategy:
        matrix:
          python-version: ["3.12"]

          steps:
            - name: scanning secrets with detect secrets
              working-directory: ./src/rally-main/rally_back
              run: detect-secrets scan .

  build-image-docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

        steps:
          - name: building docker image
            working-directory: .
            run: docker build . -t rally_back_git



